### ISSUE TITLE
Could you update the conda env yaml of the experiment enviroment?

### ISSUE THREAD

**Issue by czq693497091** [hetailang/SqueezeAttention#1]
I follow the SqueezeAttention/README.md but fails to install the crfm-helm with transformers==4.35.2. Other version of transformers cannot work with the modify transformers. I would really appreciate if the experiment env.yaml can be provided.

**Comment by hetailang** [comment]
Hi, sorry for the inconvenience caused by version conflicts.
you can install crfm-helm and transformers separately to solve this problem, we have already updated our README.md.

Please let me know if you have any other questions about our project and thank you for your interests.

**Comment by czq693497091** [comment]
In addition, can this code run in lower version of cuda like 11.7? It seems that the key version is the transformers.

**Comment by hetailang** [comment]
Yes, we provided the installation command for torch corresponding to cuda=12.1 in the file, and you can modify the command according to your own version of cuda. As long as cuda>=11.6 is ensured to meet the installation conditions for flash attention.
